# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CLICK', 'click'), ('KEYPRESS', 'keypress')], max_length=10)),
                ('os', models.CharField(max_length=30)),
                ('user_agent', models.CharField(max_length=150)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
