# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryitem',
            name='element',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
