# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_auto_20161103_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryitem',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
