# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_telemetryitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryitem',
            name='session_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
