# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_telemetryitem_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryitem',
            name='new_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='telemetryitem',
            name='event_type',
            field=models.CharField(choices=[('click', 'click'), ('keypress', 'keypress'), ('navigation', 'navigation')], max_length=10),
        ),
    ]
