# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_auto_20161202_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryitem',
            name='event_type',
            field=models.CharField(choices=[('click', 'click'), ('keypress', 'keypress'), ('navigation', 'navigation'), ('scrollend', 'scrollend'), ('focus', 'focus'), ('blur', 'blur')], max_length=10),
        ),
    ]
