# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_auto_20161206_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryitem',
            name='element',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='telemetryitem',
            name='event_type',
            field=models.CharField(choices=[('click', 'click'), ('keypress', 'keypress'), ('navigation', 'navigation'), ('scrollend', 'scrollend'), ('focus', 'focus'), ('blur', 'blur'), ('error', 'error')], max_length=10),
        ),
    ]
