# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_auto_20161209_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryitem',
            name='error_message',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
