# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0010_telemetryitem_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryitem',
            name='error_line_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
